import ProofPilotLayout from "@/components/ProofPilotLayout";
import { ArrowRight, Check, CircleDashed, Code2, Database, ExternalLink, FileCheck2, Files, LockKeyhole, MonitorPlay, Network, ScanSearch, ShieldCheck, UserRoundCheck } from "lucide-react";

const evidence = [
  { name: "Nutrient DWS", state: "Live-validated", enabled: true, detail: "Data Extraction and Processor signing were live-validated against the synthetic PDF. The signing result includes a verifiable PDF /ByteRange marker." },
  { name: "DevNetwork overall", state: "Eligible concept", detail: "Progress, real-world problem, and startup feasibility are demonstrated through the public workflow and visible architecture." },
  { name: "SerpApi", state: "Live-validated", enabled: true, detail: "Issuer and public-policy research is a reviewer-visible evidence step. Its constrained public query and returned findings are recorded in the audit trail." },
  { name: "Doctavian", state: "Optional extension", detail: "A review certificate can be added after credentials are provided; it is not represented as active in this build." },
];

const architecture = [
  { icon: Files, name: "Source PDF", detail: "Private upload or public sample" },
  { icon: ScanSearch, name: "Nutrient extraction", detail: "Fields + confidence + evidence" },
  { icon: UserRoundCheck, name: "Human review", detail: "Exception gate before approval" },
  { icon: Network, name: "Public research", detail: "SerpApi issuer evidence" },
  { icon: Database, name: "Audit ledger", detail: "Timestamped persisted decisions" },
  { icon: LockKeyhole, name: "Final artifact", detail: "Nutrient signing output" },
];

export default function Submission() {
  return <ProofPilotLayout><main className="mx-auto max-w-6xl px-4 py-8 sm:px-7 lg:px-10 lg:py-11">
    <div className="max-w-3xl"><div className="mb-3 inline-flex items-center gap-2 rounded-full bg-[#edf7f4] px-3 py-1.5 text-[10px] font-semibold uppercase tracking-[.14em] text-[#287063]"><FileCheck2 className="size-3" />Hackathon submission kit</div><h1 className="text-3xl font-semibold tracking-[-.045em] text-[#112a25] sm:text-4xl">ProofPilot makes document automation accountable.</h1><p className="mt-4 text-sm leading-7 text-slate-500">An AI-powered PDF processing workspace that extracts source-grounded data, exposes uncertainty to a human reviewer, retains the decision trail, and finalizes a document record only after review.</p></div>
    <section className="mt-8 grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-[#47776c]">One-line summary</p><p className="mt-3 text-xl font-semibold tracking-tight text-slate-800">From messy PDF to a decision you can defend.</p><div className="mt-8 border-t border-slate-100 pt-6"><p className="text-[11px] font-semibold uppercase tracking-[.14em] text-[#47776c]">Project pitch</p><p className="mt-3 text-sm leading-7 text-slate-600">Regulated teams cannot treat a document model’s answer as an approval. ProofPilot uses Nutrient DWS to turn a source PDF into confidence-scored fields, routes uncertain values to a human, records every action in a durable audit trail, and prepares a tamper-evident final output after a reviewer approves it. The result is a transparent document pipeline for the moments when “almost right” is not right enough.</p></div></article><aside className="rounded-2xl bg-[#0c302c] p-5 text-white sm:p-7"><MonitorPlay className="size-5 text-[#a7ead8]" /><p className="mt-5 text-lg font-semibold">Demo video placeholder</p><p className="mt-2 text-xs leading-5 text-[#b7d4cc]">Record a 90–120 second walkthrough: upload the sample PDF, show the flagged term, correct it, show the audit entry, and explain the finalization request.</p><div className="mt-6 grid aspect-video place-items-center rounded-xl border border-dashed border-white/20 bg-white/[.06]"><div className="text-center"><span className="mx-auto grid size-10 place-items-center rounded-full bg-white/10"><MonitorPlay className="size-4" /></span><p className="mt-2 text-[11px] font-semibold text-[#c8e3dc]">Add public demo video URL</p></div></div></aside></section>
    <section className="mt-6 overflow-hidden rounded-2xl border border-[#d9e9e4] bg-[#f2f8f5] p-5 sm:p-7"><div className="flex items-start gap-3"><span className="grid size-9 place-items-center rounded-xl bg-white text-[#287063] shadow-sm"><Network className="size-4" /></span><div><h2 className="text-sm font-semibold text-[#153d36]">Architecture judges can inspect</h2><p className="mt-1 text-xs leading-5 text-[#52756c]">ProofPilot never treats extraction as approval. It records each transition and does not create a final artifact until human review resolves uncertainty.</p></div></div><div className="mt-6 flex flex-col gap-3 lg:flex-row lg:items-stretch">{architecture.map(({ icon: Icon, name, detail }, index) => <div key={name} className="flex flex-1 items-center gap-3 rounded-xl border border-[#d5e7e1] bg-white/75 p-3.5"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-[#e4f2ed] text-[#287063]"><Icon className="size-4" /></span><div className="min-w-0"><p className="text-xs font-semibold text-[#1a5045]">{name}</p><p className="mt-0.5 text-[10px] leading-4 text-[#638078]">{detail}</p></div>{index < architecture.length - 1 && <ArrowRight className="ml-auto hidden size-4 shrink-0 text-[#7da89d] lg:block" />}</div>)}</div></section>
    <section className="mt-6 rounded-2xl border border-slate-200 bg-white p-5 sm:p-7"><div className="mb-6 flex items-start gap-3"><span className="grid size-9 place-items-center rounded-xl bg-[#eef6f3] text-[#287063]"><Network className="size-4" /></span><div><h2 className="text-sm font-semibold">Sponsor evidence matrix</h2><p className="mt-1 text-xs leading-5 text-slate-500">Only integrations that are product-critical and visible in the demo should be claimed in a submission.</p></div></div><div className="grid gap-3 md:grid-cols-2">{evidence.map(item => <div key={item.name} className="rounded-xl border border-slate-100 bg-[#fcfdfc] p-4"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold text-slate-700">{item.name}</p><span className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-[10px] font-semibold ${item.enabled ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{item.enabled ? <Check className="size-3" /> : <CircleDashed className="size-3" />}{item.state}</span></div><p className="mt-2 text-xs leading-5 text-slate-500">{item.detail}</p></div>)}</div></section>
    <section className="mt-6 grid gap-4 sm:grid-cols-3">{[{ icon: ShieldCheck, title: "Trust by design", text: "Source citations, field confidence, review gates, and a timestamped audit log." }, { icon: Code2, title: "Built to prove", text: "Live Nutrient calls and constrained SerpApi research support the visible review workflow." }, { icon: ExternalLink, title: "What remains", text: "Record the final public walkthrough, add its URL here, and obtain approval before publishing the submission." }].map(({ icon: Icon, title, text }) => <div key={title} className="rounded-2xl border border-slate-200 bg-white p-5"><Icon className="size-4 text-[#3b766a]" /><p className="mt-4 text-sm font-semibold text-slate-700">{title}</p><p className="mt-2 text-xs leading-5 text-slate-500">{text}</p></div>)}</section>
  </main></ProofPilotLayout>;
}
